/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FilesFileIdIndexImport } from './routes/files/$fileId/index'

// Create/Update Routes

const FilesFileIdIndexRoute = FilesFileIdIndexImport.update({
  path: '/files/$fileId/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/files/$fileId/': {
      preLoaderRoute: typeof FilesFileIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([FilesFileIdIndexRoute])

/* prettier-ignore-end */
