/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as FoldersFolderIdIndexImport } from './routes/folders/$folderId/index'
import { Route as FoldersFolderIdFilesFileIdIndexImport } from './routes/folders/$folderId/files/$fileId/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FoldersFolderIdIndexRoute = FoldersFolderIdIndexImport.update({
  path: '/folders/$folderId/',
  getParentRoute: () => rootRoute,
} as any)

const FoldersFolderIdFilesFileIdIndexRoute =
  FoldersFolderIdFilesFileIdIndexImport.update({
    path: '/folders/$folderId/files/$fileId/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/folders/$folderId/': {
      id: '/folders/$folderId/'
      path: '/folders/$folderId'
      fullPath: '/folders/$folderId'
      preLoaderRoute: typeof FoldersFolderIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/folders/$folderId/files/$fileId/': {
      id: '/folders/$folderId/files/$fileId/'
      path: '/folders/$folderId/files/$fileId'
      fullPath: '/folders/$folderId/files/$fileId'
      preLoaderRoute: typeof FoldersFolderIdFilesFileIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  FoldersFolderIdIndexRoute,
  FoldersFolderIdFilesFileIdIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/folders/$folderId/",
        "/folders/$folderId/files/$fileId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/folders/$folderId/": {
      "filePath": "folders/$folderId/index.tsx"
    },
    "/folders/$folderId/files/$fileId/": {
      "filePath": "folders/$folderId/files/$fileId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
