name: backend-ci

on:
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/backend.yaml"

jobs:
  execute_tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.x"
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: go get .
      - name: run tests
        run: go test ./...
