name: frontend-ci

on:
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yaml"

jobs:
  code_analysis:
    name: Run code analysis
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: pnpm install
        working-directory: frontend
      - name: Run ESLint check
        run: pnpm run lint
        working-directory: frontend
      - name: Run Prettier check
        run: pnpm run prettier:check
        working-directory: frontend
      - name: Run vitest
        run: pnpm run test
        working-directory: frontend
